# Generated by Django 3.2.13 on 2022-06-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpin',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
