# Generated by Django 3.2.13 on 2022-06-27 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_policy', '0001_privacy_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivacyPolicy',
        ),
    ]
