# Generated by Django 3.2.13 on 2022-06-27 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms_and_conditions', '0001_terms_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TermAndCondition',
        ),
    ]
